steps:
  - label: ":github: Clone and Test Repo"
    commands:
      - echo "Running on $(uname -m) architecture"
      - git clone git@github.com:abhayPS11/test1-arm64.git .
      - ls -la
    agents:
      - "arch=arm64"
